version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ap
      POSTGRES_PASSWORD: A1b2C3d4E5f6G7h8I9j0K!
      POSTGRES_DB: ap
    ports:
      - "5432:5432"
    networks:
      - APNet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ap"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://ap:A1b2C3d4E5f6G7h8I9j0K!@postgres:5432/ap
      JWT_SECRET_KEY: skdjaksjdkmasdkamskm
    ports:
      - "3333:3333"
    networks:
      - APNet
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    command: ["/bin/sh", "-c", "npx prisma migrate deploy && npm start"]

volumes:
  postgres_data:

networks:
  APNet:
    driver: bridge