-- CreateEnum
CREATE TYPE "PlanTypeEnum" AS ENUM ('pro', 'master', 'starter');

-- CreateEnum
CREATE TYPE "RegionEnum" AS ENUM ('norte', 'nordeste', 'centrooeste', 'sudeste', 'sul');

-- CreateTable
CREATE TABLE "User" (
    "USER_ID" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "Distributor" (
    "DISTRIBUTOR_ID" TEXT NOT NULL,
    "PLAN_TYPE" "PlanTypeEnum" NOT NULL,
    "ADDRESS" TEXT NOT NULL,
    "REGION" "RegionEnum" NOT NULL,
    "POSTAL_CODE" TEXT NOT NULL,
    "LONGITUDE" DOUBLE PRECISION NOT NULL,
    "LATITUDE" DOUBLE PRECISION NOT NULL,
    "WHATSAPP_NUMBER" TEXT NOT NULL,
    "PHONE_NUMBER" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Distributor_pkey" PRIMARY KEY ("DISTRIBUTOR_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_EMAIL_key" ON "User"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "Distributor_LONGITUDE_key" ON "Distributor"("LONGITUDE");

-- CreateIndex
CREATE UNIQUE INDEX "Distributor_LATITUDE_key" ON "Distributor"("LATITUDE");

-- CreateIndex
CREATE INDEX "IDX_DISTRIBUTOR_REGION" ON "Distributor"("REGION");

-- CreateIndex
CREATE INDEX "IDX_DISTRIBUTOR_POSTAL_CODE" ON "Distributor"("POSTAL_CODE");

-- CreateIndex
CREATE INDEX "IDX_DISTRIBUTOR_LATITUDE_LONGITUDE" ON "Distributor"("LATITUDE", "LONGITUDE");

-- CreateIndex
CREATE UNIQUE INDEX "Distributor_LATITUDE_LONGITUDE_key" ON "Distributor"("LATITUDE", "LONGITUDE");
